name: Rust

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        version_feature: ["--features spine38", ""]
        use_libc_feature: ["--features use_libc", ""]
        egui_debugger_feature: ["--features egui_debugger", ""]
        mint_feature: ["--features mint", ""]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install required packages
        run: sudo apt-get install libasound2-dev libudev-dev
        # Always use the draw_functions feature - the examples don't build without it, causing the test step to fail.

      - name: Build
        run: cargo build --verbose --no-default-features --features draw_functions ${{ matrix.version_feature }} ${{ matrix.use_libc_feature }} ${{ matrix.egui_debugger_feature }} ${{ matrix.mint_feature }}

      - name: Run tests
        run: cargo test --verbose --no-default-features --features draw_functions ${{ matrix.version_feature }} ${{ matrix.use_libc_feature }} ${{ matrix.egui_debugger_feature }} ${{ matrix.mint_feature }}
